/**
 * A compact built-in subdomain wordlist for DNS brute-forcing.
 * Kept intentionally small & high-signal so scans finish quickly
 * even in constrained environments.
 */
export const SUBDOMAIN_WORDLIST: string[] = [
  "www", "mail", "smtp", "imap", "pop", "pop3", "webmail", "ns1", "ns2", "ns3",
  "ns", "dns", "dns1", "dns2", "m", "mobile", "api", "api1", "api2", "app",
  "apps", "app1", "dev", "dev1", "dev2", "staging", "stage", "stg", "test",
  "testing", "test1", "qa", "sandbox", "beta", "alpha", "uat", "preprod",
  "prod", "production", "vpn", "remote", "secure", "gateway", "portal",
  "admin", "administrator", "admin1", "portal1", "cpanel", "whm", "webmin",
  "panel", "console", "manage", "manager", "control", "cp", "plesk", "backup",
  "backups", "bak", "old", "new", "v1", "v2", "v3", "demo", "demos", "shop",
  "store", "blog", "forum", "wiki", "docs", "doc", "help", "support", "kb",
  "knowledge", "cdn", "static", "assets", "media", "img", "images", "image",
  "static1", "static2", "files", "download", "downloads", "upload", "uploads",
  "ftp", "sftp", "file", "data", "db", "database", "sql", "mysql", "postgres",
  "redis", "mongo", "cache", "session", "auth", "sso", "oauth", "login",
  "signin", "signup", "register", "account", "accounts", "id", "identity",
  "saml", "ldap", "directory", "git", "gitlab", "github", "ci", "cd", "jenkins",
  "build", "builder", "deploy", "docker", "registry", "k8s", "kubernetes",
  "monitor", "monitoring", "metrics", "stats", "stat", "status", "health",
  "grafana", "prometheus", "kibana", "elastic", "log", "logs", "logging",
  "syslog", "analytics", "track", "tracker", "report", "reports", "bi",
  "internal", "intranet", "extranet", "private", "public", "external", "ext",
  "office", "corp", "corporate", "hq", "web", "web1", "web2", "www2", "www3",
  "mx", "mx1", "mx2", "relay", "outbound", "inbound", "mta", "exchange", "owa",
  "ews", "autodiscover", "imap2", "smtp2", "submit", "submission", "email",
  "mxrecord", "host", "host1", "host2", "node", "node1", "node2", "server",
  "server1", "server2", "srv", "srv1", "srv2", "vm", "vm1", "vm2", "cloud",
  "aws", "azure", "gcp", "s3", "storage", "bucket", "cdn2", "edge", "origin",
  "frontend", "backend", "ws", "wss", "websocket", "socket", "stream",
  "streaming", "live", "rtmp", "video", "audio", "chat", "msg", "mq", "queue",
  "rabbit", "kafka", "zookeeper", "etcd", "consul", "vault", "secrets", "key",
  "keys", "cert", "certs", "pki", "ca", "acme", "ssl", "tls", "proxy", "proxy1",
  "haproxy", "nginx", "apache", "httpd", "varnish", "squid", "traefik", "envoy",
  "istio", "linkerd", "ingress", "lb", "loadbalancer", "firewall", "fw", "ips",
  "ids", "waf", "ddos", "shield", "protect", "scan", "scanner", "pentest",
  "security", "sec", "audit", "logs2", "siem", "soc", "ticket", "tickets",
  "jira", "confluence", "bitbucket", "sonar", "nexus", "artifactory", "npm",
  "pypi", "maven", "gradle", "terraform", "ansible", "puppet", "chef", "salt",
  "nomad", "vault2", "consul2", "minio", "ceph", "gluster", "nfs", "samba",
  "share", "shares", "shared", "collab", "office365", "o365", "m365", "ad",
  "dc", "ldap2", "krb", "kerberos", "spnego", "ntlm", "wins", "dhcp", "tftp",
  "ntp", "snmp", "syslog2", "rsyslog", "fluent", "fluentd", "fluentbit",
  "loki", "tempo", "jaeger", "zipkin", "opentracing", "otel", "opentelemetry",
  "apm", "rum", "synthetic", "ping", "pingdom", "uptimerobot", "newrelic",
  "datadog", "splunk", "sumo", "logz", "papertrail", "sematext", "instana",
  "dynatrace", "appdynamics", "stackdriver",
];
